# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 21:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('class_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('parental_status', models.CharField(choices=[('Both Parents', 'Both Parents'), ('Single Parent', 'Single Parent'), ('Orphan', 'Orphan')], max_length=20)),
                ('family_type', models.CharField(choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=20)),
                ('siblings', models.IntegerField()),
                ('order_of_birth', models.CharField(choices=[('First Born', 'First Born'), ('Second Born', 'Second Born'), ('Last Born', 'Last Born')], max_length=30)),
                ('parent_education_level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher Secondary', 'Higher Secondary'), ('None', 'None')], max_length=20)),
                ('family_income', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningcurveapp.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('aadhar_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningcurveapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningcurveapp.Student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningcurveapp.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='schools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningcurveapp.School'),
        ),
        migrations.AlterUniqueTogether(
            name='login',
            unique_together=set([('username', 'password')]),
        ),
        migrations.AlterUniqueTogether(
            name='teacherstudent',
            unique_together=set([('teacher', 'student')]),
        ),
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together=set([('questions', 'marks')]),
        ),
    ]
