# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('parental_status', models.CharField(choices=[('Both Parents', 'Both Parents'), ('Single Parent', 'Single Parent'), ('Orphan', 'Orphan')], max_length=20)),
                ('family_type', models.CharField(choices=[('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=20)),
                ('siblings', models.IntegerField()),
                ('order_of_birth', models.CharField(max_length=30)),
                ('parent_education_level', models.CharField(choices=[('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher Secondary', 'Higher Secondary'), ('None', 'None')], max_length=20)),
                ('family_income', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('aadhar_id', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25)),
            ],
        ),
    ]
