# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningcurveapp', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='order_of_birth',
            field=models.CharField(choices=[('First Born', 'First Born'), ('Second Born', 'Second Born'), ('Last Born', 'Last Born')], max_length=30),
        ),
    ]
