# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningcurveapp', '0002_studentassessment_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentassessment',
            name='q1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='q2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='q3',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='q4',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='q5',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='q6',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='studentassessment',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='studentassessment',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
