# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningcurveapp', '0003_auto_20170715_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='order_of_birth',
            field=models.CharField(max_length=30),
        ),
    ]
