# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-16 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningcurveapp', '0003_auto_20170715_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='aadhar_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
