# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningcurveapp', '0004_auto_20170715_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='learningcurveapp.Student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='order_of_birth',
            field=models.CharField(choices=[('First Born', 'First Born'), ('Second Born', 'Second Born'), ('Last Born', 'Last Born')], max_length=30),
        ),
    ]
