# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learningcurveapp', '0005_auto_20170715_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('class_level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='master',
            name='schools',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learningcurveapp.School'),
        ),
    ]
